Programa/projetoBD/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pesquisas#index'

  get 'aulas_fds/chart', to: 'aulas_fds#chart', as: 'aulas_fds_chart'
  get 'aulas_fds/:page', to: 'aulas_fds#index', as: 'aulas_fds'
  get 'escolaridade_secundaria/chart', to: 'escolaridade_secundaria#chart', as: 'escolaridade_secundaria_chart'
  get 'escolaridade_secundaria/:page', to: 'escolaridade_secundaria#index', as: 'escolaridade_secundaria'
  get 'escolas/chart', to: 'escolas#chart', as: 'escolas_chart'
  get 'escolas/:page', to: 'escolas#index', as: 'escolas'
  get 'formacao_ur/chart', to: 'formacao_ur#chart', as: 'formacao_ur_chart'
  get 'formacao_ur/:page', to: 'formacao_ur#index', as: 'formacao_ur'
  get 'funcionarios/chart', to: 'funcionarios#chart', as: 'funcionarios_chart'
  get 'funcionarios/:page', to: 'funcionarios#index', as: 'funcionarios'
  get 'pesquisas/chart', to: 'pesquisas#chart', as: 'pesquisas_chart'
  get 'pesquisas', to: 'pesquisas#index', as: 'pesquisas'
  get 'quant_aulas/chart', to: 'quant_aulas#chart', as: 'quant_aulas_chart'
  get 'quant_aulas/:page', to: 'quant_aulas#index', as: 'quant_aulas'

end

Programa/projetoBD/app/models/aluno.rb
class Aluno < ApplicationRecord
end

Programa/projetoBD/app/models/categoriaprivada.rb
class Categoriaprivada < ApplicationRecord
end

Programa/projetoBD/app/models/cor_raca.rb
class CorRaca < ApplicationRecord
end

Programa/projetoBD/app/models/dependenciaadm.rb
class Dependenciaadm < ApplicationRecord
end

Programa/projetoBD/app/models/docente.rb
class Docente < ApplicationRecord
end

Programa/projetoBD/app/models/escola.rb
class Escola < ApplicationRecord
end

Programa/projetoBD/app/models/escolaridade.rb
class Escolaridade < ApplicationRecord
end

Programa/projetoBD/app/models/etapaensino.rb
class Etapaensino < ApplicationRecord
end

Programa/projetoBD/app/models/funcaoescolar.rb
class Funcaoescolar < ApplicationRecord
end

Programa/projetoBD/app/models/mediacaodidped.rb
class Mediacaodidped < ApplicationRecord
end

Programa/projetoBD/app/models/municipio.rb
class Municipio < ApplicationRecord
end

Programa/projetoBD/app/models/nacionalidade.rb
class Nacionalidade < ApplicationRecord
end

Programa/projetoBD/app/models/paisorigem.rb
class Paisorigem < ApplicationRecord
end

Programa/projetoBD/app/models/regiao.rb
class Regiao < ApplicationRecord
end

Programa/projetoBD/app/models/sexo.rb
class Sexo < ApplicationRecord
end

Programa/projetoBD/app/models/situacaoescola.rb
class Situacaoescola < ApplicationRecord
end

Programa/projetoBD/app/models/tipolocalizacao.rb
class Tipolocalizacao < ApplicationRecord
end

Programa/projetoBD/app/models/turma.rb
class Turma < ApplicationRecord
end

Programa/projetoBD/app/models/turmasdosaluno.rb
class Turmasdosaluno < ApplicationRecord
end

Programa/projetoBD/app/controllers/quant_aulas_controller.rb
class QuantAulasController < ApplicationController
  def index
    @pergunta = 'Quantas turmas dão aula 5 dias ou mais na semana?'
    @query = Turma.select(:idTurma, :DiasPorSemana).where('`turma`.`DiasPorSemana` >= 5').order(:DiasPorSemana).limit(20).offset(20*(params[:page].to_i-1))
  end

  def chart
    @graph = {'5 ou mais' => Turma.where('DiasPorSemana >= 5').count,
      'Menos de 5' => Turma.where('DiasPorSemana < 5').count,
      'Não disponibilizado' => Turma.where('DiasPorSemana IS NULL').count}
    render json: @graph
  end
end

Programa/projetoBD/app/helpers/escolas_helper.rb
module EscolasHelper
end

Programa/projetoBD/app/helpers/quant_aulas_helper.rb
module QuantAulasHelper
end

Programa/projetoBD/app/views/quant_aulas/index.html.erb
<div class="ui center very padded container segment">
  <h1 class="ui center header"><%= @pergunta %></h1>
  <h3 class="ui center header"><%= @query.to_sql %></h3>

  <%= pie_chart quant_aulas_chart_path %>

  <ul class="pagination">
    <% if params[:page] == '1' %>
    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a>
    <% else %>
    <li>
      <%= link_to quant_aulas_path(params[:page].to_i-1) do%>
      <i class="material-icons">chevron_left</i>
      <% end %>
    </li>
    <% end %>
    <li class="active"><a href="#!"><%= params[:page] %></a></li>
    <li class="waves-effect">
      <%= link_to quant_aulas_path(params[:page].to_i+1) do%>
      <i class="material-icons">chevron_right</i>
      <% end %>
    </li>
  </ul>

  <table class="highlight centered">
    <thead>
      <tr>
        <th>idTurma</th>
        <th>Quantidade de Aulas</th>
      </tr>
    </thead>

    <tbody>
      <% @query.each do |t| %>
      <tr>
        <td><%= t.idTurma %></td>
        <td><%= t.DiasPorSemana %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>